version: "3.4"

services:
  cron-manager:
    build:
      dockerfile: "docker/Dockerfile.dev"
      context: .
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - ./.env:/usr/src/app/.env